"use client";
import { useEffect, useMemo, useState } from "react";
import type { Room } from "@/lib/game";
import { treatInfo } from "@/lib/game";
const playerKey = "snack-attack-player";
function id() { let value = localStorage.getItem(playerKey); if (!value) { value = crypto.randomUUID(); localStorage.setItem(playerKey, value); } return value; }
async function api(url: string, body?: object) { const response = await fetch(url, body ? { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : undefined); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Try again"); return data; }
function Timer({ endsAt }: { endsAt: number | null }) { const [now, setNow] = useState(Date.now()); useEffect(() => { const t = setInterval(() => setNow(Date.now()), 250); return () => clearInterval(t); }, []); return <b className="rounded-full bg-ink px-3 py-2 text-white">{endsAt ? Math.max(0, Math.ceil((endsAt - now) / 1000)) : 0}s</b>; }
export default function Game() {
  const [name, setName] = useState(""); const [code, setCode] = useState(""); const [room, setRoom] = useState<Room | null>(null); const [error, setError] = useState(""); const playerId = useMemo(() => typeof window === "undefined" ? "" : id(), []);
  const refresh = async (roomCode: string) => { try { setRoom(await api(`/api/rooms/${roomCode}`)); } catch (e) { setError(e instanceof Error ? e.message : "Could not refresh"); } };
  useEffect(() => { if (!room) return; const timer = setInterval(() => refresh(room.code), 850); return () => clearInterval(timer); }, [room?.code]);
  const create = async () => { try { if (!name.trim()) throw new Error("Enter your name first"); setRoom(await api("/api/rooms", { playerId, name })); } catch (e) { setError(e instanceof Error ? e.message : "Could not create room"); } };
  const join = async () => { try { if (!name.trim() || code.length !== 6) throw new Error("Add your name and a 6-character code"); setRoom(await api(`/api/rooms/${code}/action`, { action: "join", playerId, name })); } catch (e) { setError(e instanceof Error ? e.message : "Could not join"); } };
  const action = async (action: string, extra = {}) => { if (!room) return; try { setRoom(await api(`/api/rooms/${room.code}/action`, { action, playerId, ...extra })); } catch (e) { setError(e instanceof Error ? e.message : "Try again"); } };
  if (!room) return <main className="mx-auto flex min-h-screen max-w-md items-center p-4"><section className="bubble w-full rounded-[2rem] bg-white p-7 text-center"><div className="text-7xl">🐶🍪</div><h1 className="mt-3 font-display text-4xl uppercase leading-none">Snack Attack</h1><p className="mt-2 font-black text-violet">FRENCHIE EDITION</p><p className="mt-4 font-bold">Chomp the treats before the other Frenchies do.</p><div className="mt-6 space-y-3 text-left"><input value={name} onChange={e => setName(e.target.value)} placeholder="Your name" maxLength={18} className="w-full rounded-xl border-3 border-ink p-3 font-bold" /><button onClick={create} className="wiggle w-full rounded-xl bg-coral p-3 font-black text-white">CREATE ROOM</button><div className="flex gap-2"><input value={code} onChange={e => setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 6))} placeholder="ROOM CODE" className="min-w-0 flex-1 rounded-xl border-3 border-ink p-3 text-center font-black tracking-widest"/><button onClick={join} className="wiggle rounded-xl bg-violet px-4 font-black text-white">JOIN</button></div></div>{error && <p className="mt-3 font-bold text-red-600">{error}</p>}</section></main>;
  const ranking = [...room.players].sort((a,b) => b.score - a.score); const isHost = room.hostId === playerId;
  return <main className="mx-auto min-h-screen max-w-md p-3 pb-10"><header className="mb-2 flex items-center justify-between"><div><div className="font-display text-2xl uppercase leading-none">Snack Attack</div><small className="font-black text-violet">FRENCHIE EDITION</small></div>{room.phase === "playing" && <Timer endsAt={room.endsAt}/>}</header>
    {room.phase === "lobby" && <section className="bubble rounded-[2rem] bg-white p-6 text-center"><p className="font-black uppercase tracking-widest">Bark this code to your friends</p><div className="my-3 font-display text-5xl tracking-[.15em]">{room.code}</div><div className="mb-6 flex flex-wrap justify-center gap-2">{room.players.map(p => <span key={p.id} className="rounded-full bg-peach px-3 py-2 font-black">🐶 {p.name}{p.id === room.hostId ? " 👑" : ""}</span>)}</div>{isHost ? <button onClick={() => action("start")} disabled={room.players.length < 2} className="wiggle w-full rounded-xl bg-coral p-4 font-black text-white disabled:opacity-40">{room.players.length < 2 ? "WAITING FOR FRENCHIES…" : "RELEASE THE TREATS!"}</button> : <p className="font-black">Waiting for the host to open the snack cupboard…</p>}</section>}
    {room.phase === "playing" && <><section className="bubble rounded-[2rem] bg-white p-3"><div className="mb-3 flex items-center justify-between rounded-2xl bg-peach px-4 py-3"><span className="font-display text-xl uppercase">Round {room.round}/8</span><span className="font-black">CHOMP FAST! 🐶</span></div><div className="relative h-[480px] overflow-hidden rounded-3xl border-3 border-ink bg-[radial-gradient(circle_at_center,_#fff8e6,_#d7c8ff)]">{room.treats.map(t => <button key={t.id} onClick={() => action("chomp", { treatId: t.id })} disabled={!!t.claimedBy} title={treatInfo[t.kind].name} style={{ left: `${t.x}%`, top: `${t.y}%` }} className={`absolute -translate-x-1/2 -translate-y-1/2 rounded-full p-1 text-4xl transition active:scale-75 ${t.claimedBy ? "scale-0 opacity-0" : "animate-bounce hover:scale-125"}`}>{treatInfo[t.kind].emoji}</button>)}<div className="pointer-events-none absolute inset-x-0 bottom-2 text-center text-5xl">🐶　🐶　🐶</div></div><p className="mt-3 text-center text-sm font-bold">🥐 +3 · 🦴/🍓 +2 · 🍪 +1 · 🥦/🎾 are a trap!</p></section><Score players={ranking}/></>}
    {(room.phase === "results" || room.phase === "finished") && <section className="bubble rounded-[2rem] bg-white p-6 text-center"><div className="text-6xl">{room.phase === "finished" ? "🏆" : "🐶💨"}</div><h2 className="font-display text-3xl uppercase">{room.phase === "finished" ? "Top Frenchie!" : "Treat Time!"}</h2><Score players={ranking}/>{room.phase === "results" && (isHost ? <button onClick={() => action("next")} className="wiggle w-full rounded-xl bg-violet p-3 font-black text-white">NEXT SNACK ROUND</button> : <p className="font-black">Waiting for the snack master…</p>)}{room.phase === "finished" && <p className="font-black">Eight rounds. So many snacks. No regrets. 🎉</p>}</section>}
    {error && <p className="mt-3 text-center font-bold text-red-600">{error}</p>}</main>;
}
function Score({ players }: { players: Room["players"] }) { return <ol className="my-4 space-y-2">{players.map((p, i) => <li key={p.id} className="flex justify-between rounded-xl bg-peach px-4 py-3 font-black"><span>{i + 1}. {p.name}</span><span>{p.score} treats</span></li>)}</ol>; }
